### ISSUE TITLE
How to get playbackPosition out of a generator?

### ISSUE THREAD

**Issue by emperor-limitless** [chrisnorman7/dart_synthizer#2]
Hi

How to get playbackPosition out of a generator? I tried
final val = generator.playbackPosition;
And
final val = generator.playback_position;
However, None of this works, Did it get renamed to something else?

Regards.

**Comment by chrisnorman7** [comment]
Hi,
You can't find it, because apparently I forgot to add it.

I'll do that later.

From the way you're writing your issues, it sounds like you might not have
found the docs <https://pub.dev/documentation/dart_synthizer/latest/>.

Thank you for reporting, keep 'em coming until there's none left!

Take care,

Chris Norman

**Comment by emperor-limitless** [comment]
Ah, Thanks, Useful.

**Comment by chrisnorman7** [comment]
Just as an FYI, all documentation links follow the same format in dart.

If you can find something on pub.dev, you can find its documentation.

Take care,

Chris Norman

**Comment by chrisnorman7** [comment]
OK, I just fixed this, but I'm an idiot and and referenced the wrong issue.

Fixed with commit 44e0574ae0c4ac9b9c1a9fa3ec73975b3e21d90d.
